# Generated by Django 4.2 on 2023-06-02 10:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_title_notes_note_title_notes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
